name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        working-directory: ./
        run: terraform init

      - name: Plan Terraform changes
        working-directory: ./
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        working-directory: ./
        run: terraform apply -auto-approve tfplan
